-- =========================================================
-- CEGONHA BABY STORE V22 - AVALIACOES COMPARTILHADAS
-- Execute UMA vez no SQL Editor do Supabase.
-- Depois publique os arquivos V22 no GitHub/Vercel.
-- =========================================================

-- 1) Tabela central de avaliações.
create table if not exists public.avaliacoes (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    produto_id bigint not null references public.produtos(id) on delete cascade,
    cliente_id text not null,
    nome text,
    nota smallint not null check (nota between 1 and 5),
    comentario text,
    constraint avaliacoes_produto_cliente_unique unique (produto_id, cliente_id),
    constraint avaliacoes_cliente_id_tamanho check (char_length(cliente_id) between 16 and 120),
    constraint avaliacoes_nome_tamanho check (char_length(coalesce(nome, '')) <= 40),
    constraint avaliacoes_comentario_tamanho check (char_length(coalesce(comentario, '')) <= 300)
);

alter table public.avaliacoes enable row level security;

create index if not exists avaliacoes_produto_id_idx on public.avaliacoes(produto_id);
create index if not exists avaliacoes_created_at_idx on public.avaliacoes(created_at desc);

-- A tabela não é acessada diretamente pelo visitante. O site usa as funções abaixo.
revoke all on table public.avaliacoes from anon, authenticated;

-- 2) Lista pública, sem expor o identificador privado do aparelho.
create or replace function public.listar_avaliacoes_publicas()
returns table (
    id bigint,
    produto_id bigint,
    nome text,
    nota smallint,
    comentario text,
    created_at timestamptz,
    updated_at timestamptz
)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
    select
        a.id,
        a.produto_id,
        a.nome,
        a.nota,
        a.comentario,
        a.created_at,
        a.updated_at
    from public.avaliacoes a
    order by a.created_at desc;
$$;

revoke all on function public.listar_avaliacoes_publicas() from public;
grant execute on function public.listar_avaliacoes_publicas() to anon, authenticated;

-- 3) Retorna somente as avaliações pertencentes ao identificador privado deste aparelho.
create or replace function public.listar_minhas_avaliacoes(p_cliente_id text)
returns table (
    id bigint,
    produto_id bigint,
    nome text,
    nota smallint,
    comentario text,
    created_at timestamptz,
    updated_at timestamptz
)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
    select
        a.id,
        a.produto_id,
        a.nome,
        a.nota,
        a.comentario,
        a.created_at,
        a.updated_at
    from public.avaliacoes a
    where a.cliente_id = left(trim(coalesce(p_cliente_id, '')), 120)
    order by a.created_at desc;
$$;

revoke all on function public.listar_minhas_avaliacoes(text) from public;
grant execute on function public.listar_minhas_avaliacoes(text) to anon, authenticated;

-- 4) Cria ou atualiza UMA avaliação por aparelho para cada produto.
create or replace function public.salvar_avaliacao(
    p_produto_id bigint,
    p_cliente_id text,
    p_nome text,
    p_nota integer,
    p_comentario text
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_id bigint;
    v_cliente_id text := left(trim(coalesce(p_cliente_id, '')), 120);
    v_nome text := nullif(left(trim(coalesce(p_nome, '')), 40), '');
    v_comentario text := nullif(left(trim(coalesce(p_comentario, '')), 300), '');
begin
    if char_length(v_cliente_id) < 16 then
        raise exception 'Identificador de avaliação inválido.';
    end if;

    if p_nota is null or p_nota < 1 or p_nota > 5 then
        raise exception 'A nota deve ficar entre 1 e 5.';
    end if;

    if not exists (
        select 1
        from public.produtos p
        where p.id = p_produto_id
          and p.ativo = true
    ) then
        raise exception 'Produto indisponível para avaliação.';
    end if;

    insert into public.avaliacoes (
        produto_id,
        cliente_id,
        nome,
        nota,
        comentario
    )
    values (
        p_produto_id,
        v_cliente_id,
        v_nome,
        p_nota::smallint,
        v_comentario
    )
    on conflict (produto_id, cliente_id)
    do update set
        nome = excluded.nome,
        nota = excluded.nota,
        comentario = excluded.comentario,
        updated_at = now()
    returning id into v_id;

    return v_id;
end;
$$;

revoke all on function public.salvar_avaliacao(bigint, text, text, integer, text) from public;
grant execute on function public.salvar_avaliacao(bigint, text, text, integer, text) to anon, authenticated;

-- 5) Exclusão/moderação pelo painel administrativo.
create or replace function public.admin_excluir_avaliacao(p_avaliacao_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
    if (select auth.uid()) is null or not exists (
        select 1
        from public.administradores a
        where a.user_id = (select auth.uid())
    ) then
        raise exception 'Acesso de administrador necessário.';
    end if;

    delete from public.avaliacoes
    where id = p_avaliacao_id;

    return found;
end;
$$;

revoke all on function public.admin_excluir_avaliacao(bigint) from public;
grant execute on function public.admin_excluir_avaliacao(bigint) to authenticated;
