-- =========================================================
-- CEGONHA BABY STORE V24 - REGISTRO DE PEDIDOS
-- Execute UMA vez no SQL Editor do Supabase.
-- Mantém a finalização pelo WhatsApp e registra o pedido no banco.
-- =========================================================

-- 1) Pedido principal.
create table if not exists public.pedidos (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    codigo text unique,
    token text not null unique,
    cliente_id text,
    cliente_nome text not null,
    cliente_telefone text not null,
    observacao text,
    total numeric(12,2) not null check (total >= 0),
    status text not null default 'novo' check (
        status in ('novo','confirmado','preparando','entregue','cancelado')
    ),
    origem text not null default 'whatsapp',
    constraint pedidos_nome_tamanho check (char_length(cliente_nome) between 2 and 80),
    constraint pedidos_telefone_tamanho check (char_length(cliente_telefone) between 8 and 20),
    constraint pedidos_observacao_tamanho check (char_length(coalesce(observacao, '')) <= 500),
    constraint pedidos_token_tamanho check (char_length(token) between 16 and 120)
);

-- 2) Itens do pedido. Guardamos nome e preço do momento da compra para manter histórico.
create table if not exists public.pedido_itens (
    id bigint generated by default as identity primary key,
    pedido_id bigint not null references public.pedidos(id) on delete cascade,
    produto_id bigint references public.produtos(id) on delete set null,
    nome_produto text not null,
    preco_unitario numeric(12,2) not null check (preco_unitario >= 0),
    quantidade integer not null check (quantidade between 1 and 99),
    subtotal numeric(12,2) not null check (subtotal >= 0)
);

create index if not exists pedidos_created_at_idx on public.pedidos(created_at desc);
create index if not exists pedidos_status_idx on public.pedidos(status);
create index if not exists pedido_itens_pedido_id_idx on public.pedido_itens(pedido_id);

alter table public.pedidos enable row level security;
alter table public.pedido_itens enable row level security;

-- Visitantes não acessam as tabelas diretamente; usam somente a função criar_pedido.
revoke all on table public.pedidos from anon;
revoke all on table public.pedido_itens from anon;

-- Administradores podem consultar os pedidos e alterar o status.
grant select, update on table public.pedidos to authenticated;
grant select on table public.pedido_itens to authenticated;

-- Políticas do painel administrativo.
drop policy if exists "Administradores podem ver pedidos" on public.pedidos;
create policy "Administradores podem ver pedidos"
on public.pedidos
for select
to authenticated
using (
    exists (
        select 1 from public.administradores a
        where a.user_id = (select auth.uid())
    )
);

drop policy if exists "Administradores podem alterar pedidos" on public.pedidos;
create policy "Administradores podem alterar pedidos"
on public.pedidos
for update
to authenticated
using (
    exists (
        select 1 from public.administradores a
        where a.user_id = (select auth.uid())
    )
)
with check (
    exists (
        select 1 from public.administradores a
        where a.user_id = (select auth.uid())
    )
);

drop policy if exists "Administradores podem ver itens dos pedidos" on public.pedido_itens;
create policy "Administradores podem ver itens dos pedidos"
on public.pedido_itens
for select
to authenticated
using (
    exists (
        select 1 from public.administradores a
        where a.user_id = (select auth.uid())
    )
);

-- 3) Função pública segura para registrar pedido.
-- O total é calculado usando os preços atuais da tabela produtos, não os valores enviados pelo navegador.
create or replace function public.criar_pedido(
    p_token text,
    p_cliente_id text,
    p_cliente_nome text,
    p_cliente_telefone text,
    p_observacao text,
    p_itens jsonb
)
returns table (
    pedido_id bigint,
    codigo text,
    total numeric
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_token text := left(trim(coalesce(p_token, '')), 120);
    v_cliente_id text := nullif(left(trim(coalesce(p_cliente_id, '')), 120), '');
    v_nome text := left(trim(coalesce(p_cliente_nome, '')), 80);
    v_telefone text := regexp_replace(coalesce(p_cliente_telefone, ''), '[^0-9+]', '', 'g');
    v_observacao text := nullif(left(trim(coalesce(p_observacao, '')), 500), '');
    v_pedido_id bigint;
    v_codigo text;
    v_total numeric(12,2) := 0;
    v_item jsonb;
    v_produto public.produtos%rowtype;
    v_quantidade integer;
    v_existente public.pedidos%rowtype;
begin
    if char_length(v_token) < 16 then
        raise exception 'Token de pedido inválido.';
    end if;

    -- Idempotência: um duplo clique/reenvio do mesmo token não duplica o pedido.
    select * into v_existente
    from public.pedidos p
    where p.token = v_token;

    if found then
        return query select v_existente.id, v_existente.codigo, v_existente.total;
        return;
    end if;

    if char_length(v_nome) < 2 then
        raise exception 'Informe o nome do cliente.';
    end if;

    if char_length(v_telefone) < 8 or char_length(v_telefone) > 20 then
        raise exception 'Informe um telefone válido.';
    end if;

    if p_itens is null or jsonb_typeof(p_itens) <> 'array' or jsonb_array_length(p_itens) = 0 then
        raise exception 'O pedido precisa ter pelo menos um item.';
    end if;

    if jsonb_array_length(p_itens) > 50 then
        raise exception 'Quantidade de itens acima do permitido.';
    end if;

    -- Valida todos os itens e calcula o total com preços do banco.
    for v_item in select value from jsonb_array_elements(p_itens)
    loop
        v_quantidade := greatest(1, least(99, coalesce((v_item->>'quantidade')::integer, 1)));

        select * into v_produto
        from public.produtos p
        where p.id = (v_item->>'produto_id')::bigint
          and p.ativo = true;

        if not found then
            raise exception 'Um dos produtos não está mais disponível.';
        end if;

        v_total := v_total + (v_produto.preco * v_quantidade);
    end loop;

    insert into public.pedidos (
        token, cliente_id, cliente_nome, cliente_telefone,
        observacao, total, status, origem
    ) values (
        v_token, v_cliente_id, v_nome, v_telefone,
        v_observacao, v_total, 'novo', 'whatsapp'
    )
    returning id into v_pedido_id;

    v_codigo := 'CEG-' || lpad(v_pedido_id::text, 6, '0');

    update public.pedidos
    set codigo = v_codigo
    where id = v_pedido_id;

    -- Grava o retrato dos produtos no momento do pedido.
    for v_item in select value from jsonb_array_elements(p_itens)
    loop
        v_quantidade := greatest(1, least(99, coalesce((v_item->>'quantidade')::integer, 1)));

        select * into v_produto
        from public.produtos p
        where p.id = (v_item->>'produto_id')::bigint;

        insert into public.pedido_itens (
            pedido_id, produto_id, nome_produto, preco_unitario, quantidade, subtotal
        ) values (
            v_pedido_id,
            v_produto.id,
            v_produto.nome,
            v_produto.preco,
            v_quantidade,
            v_produto.preco * v_quantidade
        );
    end loop;

    return query select v_pedido_id, v_codigo, v_total;
end;
$$;

revoke all on function public.criar_pedido(text, text, text, text, text, jsonb) from public;
grant execute on function public.criar_pedido(text, text, text, text, text, jsonb) to anon, authenticated;
